language: node_js
node_js:
  - "8.12.0"
script:
  - yarn run lint --no-fix --max-warnings 0
  - yarn run build
deploy:
  provider: pages
  skip-clean: true
  github-token: $GH_PROG_PRES_TOKEN
  local-dir: dist
  on:
    branch: master
